apiVersion: v1
kind: Service
metadata:
  name: clamav
  labels:
    app.kubernetes.io/name: clamav
    app.kubernetes.io/component: dependency
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clamav
  ports:
    - name: clamd
      protocol: TCP
      port: 3310
      targetPort: 3310
