apiVersion: v1
kind: Service
metadata:
  name: codex-creator
  labels:
    app.kubernetes.io/name: codex-creator
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: codex-creator
  ports:
    - name: http
      port: 8090
      targetPort: http
