apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: dependency
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kibana
  ports:
    - name: http
      protocol: TCP
      port: 5601
      targetPort: 5601
      appProtocol: http
