apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-service.yaml
  - redis-service.yaml
  - rabbitmq-service.yaml
  - elasticsearch-service.yaml
  - kibana-service.yaml
  - clamav-service.yaml
