package com.biliwind.blog.service;

import jakarta.enterprise.context.ApplicationScoped;
import org.eclipse.microprofile.config.inject.ConfigProperty;

/**
 * Provides one canonical public origin for links generated by the application.
 * The value is deployment configuration, not user content, so email, SEO and AMP
 * links cannot silently diverge between database setting keys.
 */
@ApplicationScoped
public class PublicUrlService {

    @ConfigProperty(name = "windblog.site.public-url", defaultValue = "http://localhost:8080")
    String configuredPublicUrl;

    public String getBaseUrl() {
        return normalize(configuredPublicUrl);
    }

    public String buildPath(String path) {
        String normalizedPath = path;
        if (normalizedPath == null || normalizedPath.isBlank()) {
            normalizedPath = "/";
        }
        if (!normalizedPath.startsWith("/")) {
            normalizedPath = "/" + normalizedPath;
        }
        return getBaseUrl() + normalizedPath;
    }

    public static String normalize(String value) {
        if (value == null || value.isBlank()) {
            return "http://localhost:8080";
        }
        String normalized = value.trim();
        while (normalized.endsWith("/") && normalized.length() > 1) {
            normalized = normalized.substring(0, normalized.length() - 1);
        }
        return normalized;
    }
}
