apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: dependency
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
