apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-data
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: dependency
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
