apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-pvc.yaml
  - postgresql-deployment.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - rabbitmq-pvc.yaml
  - rabbitmq-deployment.yaml
  - elasticsearch-pvc.yaml
  - elasticsearch-deployment.yaml
  - kibana-pvc.yaml
  - kibana-deployment.yaml
  - clamav-pvc.yaml
  - clamav-deployment.yaml
  - windblog-deployment.yaml
  - codex-creator-deployment.yaml
