apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: dependency
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
